# shellcheck shell=bash
# GPU detection and Compose override generation (ROADMAP PR 2).
# Sourced by the installer. Depends on log/warn from atlas-lib.sh.

# detect_gpu_backend — best-effort host detection: nvidia > vulkan(amd) > cpu.
# ROCm is only chosen when explicitly requested (legacy AMD prefers Vulkan).
detect_gpu_backend() {
  if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then
    echo nvidia
    return
  fi
  if compgen -G "/dev/dri/renderD*" >/dev/null 2>&1; then
    echo vulkan
    return
  fi
  echo cpu
}

# gpu_group_id NAME — numeric GID for a group (empty if absent).
gpu_group_id() {
  getent group "$1" 2>/dev/null | cut -d: -f3
}

# generate_gpu_override ROOT BACKEND — write .atlas/docker-compose.gpu.yml (or remove for cpu).
generate_gpu_override() {
  local root="$1" backend="$2"
  local dir="$root/.atlas" out="$root/.atlas/docker-compose.gpu.yml"
  mkdir -p "$dir"

  case "$backend" in
    nvidia)
      cat > "$out" <<'YAML'
# Generated by ATLAS installer — NVIDIA GPU acceleration for Ollama.
services:
  ollama:
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
YAML
      log "Wrote NVIDIA GPU override: $out"
      ;;
    vulkan|rocm)
      local video render
      video="$(gpu_group_id video)"
      render="$(gpu_group_id render)"
      {
        echo "# Generated by ATLAS installer — AMD ${backend^^} acceleration for Ollama."
        echo "services:"
        echo "  ollama:"
        echo "    devices:"
        echo "      - /dev/dri:/dev/dri"
        [ -e /dev/kfd ] && echo "      - /dev/kfd:/dev/kfd"
        if [ -n "$video" ] || [ -n "$render" ]; then
          echo "    group_add:"
          [ -n "$video" ]  && echo "      - \"$video\""
          [ -n "$render" ] && echo "      - \"$render\""
        fi
        echo "    environment:"
        if [ "$backend" = "vulkan" ]; then
          echo "      OLLAMA_VULKAN: \"1\""
        fi
        echo "      OLLAMA_DEBUG: \"1\""
      } > "$out"
      log "Wrote ${backend} GPU override: $out (video=${video:-none} render=${render:-none})"
      ;;
    cpu)
      rm -f "$out"
      log "GPU disabled (cpu); removed any GPU override."
      ;;
    *)
      warn "Unknown GPU backend '$backend'; not generating an override."
      ;;
  esac
}

# gpu_backend_configured ROOT — the backend ATLAS is configured to use for Ollama,
# read from the generated compose override (cpu when none). Pure/testable.
gpu_backend_configured() {
  local f="$1/.atlas/docker-compose.gpu.yml"
  if [ ! -f "$f" ]; then echo cpu; return; fi
  if grep -q "driver: nvidia" "$f"; then echo nvidia
  elif grep -q "OLLAMA_VULKAN" "$f"; then echo vulkan
  elif grep -q "/dev/kfd" "$f"; then echo rocm
  else echo custom; fi
}

# check_render_permissions — warn if the user cannot access the render node.
check_render_permissions() {
  local target_user="${1:-$(id -un)}"
  local dev
  for dev in /dev/dri/renderD*; do
    [ -e "$dev" ] || continue
    if ! sudo -u "$target_user" test -r "$dev" 2>/dev/null && [ "$target_user" != root ]; then
      warn "User '$target_user' may lack access to $dev — add to 'video'/'render' groups and re-login."
    fi
  done
}
