/**
 * UI strings as [English, Italian] pairs. Merged into the i18n dictionaries;
 * use `{name}` placeholders for values passed to t(key, { name }).
 */
export const STRINGS: Record<string, [string, string]> = {
  "lang.auto": ["Automatic (system)", "Automatica (sistema)"],
  "chat.cmd.help": ["Commands you can type here:\n• /web <question> — answer using a web search (cites sources)\n• /search <query> — show web results only\n• /remember <text> — save a memory\n• /recall <query> — recall saved memories\n• /model <name> — pick the model (or /models to list)\n• /task <title> — create a task · /nodes — list nodes · /status — health\n• /help — show this help", "Comandi che puoi scrivere qui:\n• /web <domanda> — risponde cercando sul web (con le fonti)\n• /search <ricerca> — mostra solo i risultati web\n• /remember <testo> — salva un ricordo\n• /recall <ricerca> — richiama i ricordi salvati\n• /model <nome> — sceglie il modello (o /models per l'elenco)\n• /task <titolo> — crea un'attività · /nodes — elenco nodi · /status — stato\n• /help — mostra questo aiuto"],
  "chat.cmd.rememberUsage": ["Usage: /remember <text>", "Uso: /remember <testo>"],
  "chat.cmd.saved": ["🧠 Saved to memory: “{text}”", "🧠 Salvato in memoria: “{text}”"],
  "chat.cmd.memories": ["🧠 Memories:", "🧠 Ricordi:"],
  "chat.cmd.noMemories": ["No memories found.", "Nessun ricordo trovato."],
  "chat.cmd.results": ["🔎 {n} result(s) for “{q}”:", "🔎 {n} risultati per “{q}”:"],
  "chat.cmd.noResults": ["No results for “{q}”.", "Nessun risultato per “{q}”."],
  "chat.cmd.models": ["Available models:", "Modelli disponibili:"],
  "chat.cmd.current": ["Current: {model}", "In uso: {model}"],
  "chat.cmd.noModels": ["No models yet — download one from the Models page.", "Ancora nessun modello: scaricane uno dalla pagina Modelli."],
  "chat.cmd.modelUsage": ["Current model: {model}. Usage: /model <name>", "Modello in uso: {model}. Uso: /model <nome>"],
  "chat.cmd.modelSet": ["✅ This chat will use model: {model}", "✅ Questa chat userà il modello: {model}"],
  "chat.cmd.taskUsage": ["Usage: /task <title>", "Uso: /task <titolo>"],
  "chat.cmd.taskCreated": ["📋 Task created: “{title}” ({status}).", "📋 Attività creata: “{title}” ({status})."],
  "chat.cmd.nodes": ["🖥️ {online}/{total} online:", "🖥️ {online}/{total} online:"],
  "chat.cmd.noNodes": ["No nodes registered.", "Nessun nodo registrato."],
  "chat.cmd.unknown": ["Unknown command “/{cmd}”. Type /help.", "Comando sconosciuto “/{cmd}”. Scrivi /help."],
  "chat.noOutput": ["(no output)", "(nessuna risposta)"],
  "chat.stopped": ["stopped", "interrotta"],
  "common.failed": ["Something went wrong", "Qualcosa è andato storto"],
  "common.online": ["online", "online"],
  "common.offline": ["offline", "offline"],
  "v.active": ["Active", "Attivo"],
  "v.analyzed": ["Analyzed", "Analizzato"],
  "v.analyzing": ["Analyzing", "In analisi"],
  "v.applied": ["Applied", "Applicato"],
  "v.approved": ["Approved", "Approvato"],
  "v.archived": ["Archived", "Archiviato"],
  "v.canary": ["Canary", "Canary"],
  "v.cancelled": ["Cancelled", "Annullato"],
  "v.completed": ["Completed", "Completato"],
  "v.complete": ["Complete", "Completo"],
  "v.draft": ["Draft", "Bozza"],
  "v.experimented": ["Tested (A/B)", "Sperimentato (A/B)"],
  "v.failed": ["Failed", "Fallito"],
  "v.fix_proposed": ["Fix proposed", "Correzione proposta"],
  "v.healthy": ["Healthy", "Sano"],
  "v.ignored": ["Ignored", "Ignorato"],
  "v.incompatible": ["Incompatible", "Incompatibile"],
  "v.needs_approval": ["Needs approval", "Da approvare"],
  "v.open": ["Open", "Aperto"],
  "v.patched": ["Patched", "Corretto"],
  "v.pending": ["Pending", "In attesa"],
  "v.prepared": ["Prepared", "Preparato"],
  "v.pr_opened": ["PR opened", "PR aperta"],
  "v.queued": ["Queued", "In coda"],
  "v.rejected": ["Rejected", "Rifiutato"],
  "v.resolved": ["Resolved", "Risolto"],
  "v.response_imported": ["Response imported", "Risposta importata"],
  "v.retrying": ["Retrying", "Nuovo tentativo"],
  "v.revoked": ["Revoked", "Revocato"],
  "v.rolled_back": ["Rolled back", "Ripristinato"],
  "v.rolling": ["Rolling out", "In distribuzione"],
  "v.running": ["Running", "In esecuzione"],
  "v.skipped_offline": ["Skipped (offline)", "Saltato (offline)"],
  "v.tested": ["Tested", "Testato"],
  "v.updating": ["Updating", "In aggiornamento"],
  "v.validated": ["Validated", "Validato"],
  "v.waiting_dependency": ["Waiting for dependency", "In attesa di dipendenza"],
  "v.waiting_external": ["Waiting for external reply", "In attesa di risposta esterna"],
  "v.critical": ["Critical", "Critico"],
  "v.high": ["High", "Alto"],
  "v.medium": ["Medium", "Medio"],
  "v.low": ["Low", "Basso"],
  "v.accept": ["Accept", "Accetta"],
  "v.reject": ["Reject", "Rifiuta"],
  "v.revise": ["Revise", "Rivedi"],
  "v.quarantine": ["Quarantine", "Quarantena"],
  "v.reinstate": ["Reinstate", "Reintegra"],
  "v.remediate": ["Remediate", "Correggi"],
  "v.degraded": ["Degraded", "Degradato"],
  "v.unhealthy": ["Unhealthy", "Non funzionante"],
  "v.online": ["Online", "Online"],
  "v.offline": ["Offline", "Offline"],
  "v.up": ["Up", "Attivo"],
  "v.down": ["Down", "Non raggiungibile"],
  "v.ok": ["OK", "OK"],
  "v.error": ["Error", "Errore"],
  "v.unknown": ["Unknown", "Sconosciuto"],
  "v.enabled": ["Enabled", "Abilitato"],
  "v.disabled": ["Disabled", "Disabilitato"],
  "v.stopped": ["Stopped", "Fermo"],
  "v.idle": ["Idle", "Inattivo"],
  "v.closed": ["Closed", "Chiuso"],
  "v.half_open": ["Half-open", "Semi-aperto"],
  "v.quarantined": ["Quarantined", "In quarantena"],
  "v.improvement": ["Improvement", "Miglioramento"],
  "v.regression": ["Regression", "Regressione"],
  "v.neutral": ["Neutral", "Neutro"],
  "v.admin": ["Admin", "Amministratore"],
  "v.user": ["User", "Utente"],
  "v.assistant": ["Assistant", "Assistente"],
  "v.system": ["System", "Sistema"],
  "common.backendError": ["Unable to reach backend: {error}", "Backend non raggiungibile: {error}"],
  "common.never": ["never", "mai"],
  "common.agoS": ["{n}s ago", "{n}s fa"],
  "common.agoM": ["{n}m ago", "{n} min fa"],
  "common.agoH": ["{n}h ago", "{n} h fa"],
  "common.dismiss": ["Dismiss", "Chiudi"],
  "common.approve": ["Approve", "Approva"],
  "common.reject": ["Reject", "Rifiuta"],
  "common.revoke": ["Revoke", "Revoca"],
  "nodes.subtitle": ["Registered worker nodes and their live heartbeat status.", "Nodi di lavoro registrati e il loro stato in tempo reale."],
  "nodes.onlineCount": ["{online} of {total} nodes online", "{online} di {total} nodi online"],
  "nodes.empty1": ["No nodes registered yet. Install a node with", "Nessun nodo registrato. Installa un nodo con"],
  "nodes.empty2": ["and start it with", "e avvialo con"],
  "nodes.nodeId": ["Node id", "ID nodo"],
  "nodes.host": ["Host", "Host"],
  "nodes.capabilities": ["Capabilities", "Capacità"],
  "nodes.lastHeartbeat": ["Last heartbeat", "Ultimo segnale"],
  "nodes.enrollment": ["Enrollment", "Registrazione nodi"],
  "nodes.enrollmentHelp": ["Per-node credentials with an approval gate. Enforced only when", "Credenziali per nodo con approvazione. Applicate solo con"],
  "nodes.nodeIdPh": ["node id (e.g. worker-2)", "ID nodo (es. worker-2)"],
  "nodes.labelPh": ["label (optional)", "etichetta (facoltativa)"],
  "nodes.invite": ["Invite", "Invita"],
  "nodes.tokenFor": ["One-time token for", "Token monouso per"],
  "nodes.tokenOnce": ["copy it now, it is not shown again. Set it on the node as", "copialo ora, non verrà più mostrato. Impostalo sul nodo come"],
  "nodes.token": ["Token", "Token"],
  "nodes.rotate": ["Rotate", "Rinnova"],
  "zt.title": ["Overlay network — ZeroTier", "Rete overlay — ZeroTier"],
  "zt.disabled1": ["Controller disabled. Nodes still join the overlay via the installer. To manage members here, set", "Controller disabilitato. I nodi entrano comunque nella rete tramite l'installer. Per gestire i membri da qui imposta"],
  "zt.disabled2": ["an API token and a network id.", "un token API e un ID di rete."],
  "zt.network": ["Network", "Rete"],
  "zt.members": ["Members", "Membri"],
  "zt.authorizedCount": ["{n}/{total} authorized", "{n}/{total} autorizzati"],
  "zt.member": ["Member", "Membro"],
  "zt.access": ["Access", "Accesso"],
  "zt.noMembers": ["No members.", "Nessun membro."],
  "common.yes": ["yes", "sì"],
  "common.no": ["no", "no"],
  "wizard.modelPh": ["model (e.g. qwen2.5:3b)", "modello (es. qwen2.5:3b)"],
  "wizard.download": ["download", "download"],
  "wizard.endpointPh": ["endpoint (e.g. http://10.147.x.x:11434)", "endpoint (es. http://10.147.x.x:11434)"],
  "fleet.subtitle": ["Roll a version out to the node fleet safely: a canary wave first, a health gate before promoting the rest, then a rolling wave — with automatic rollback on failure. Offline nodes and nodes below the compatibility floor are skipped. Nodes apply their desired_version and report back.", "Distribuisci una versione alla flotta di nodi in sicurezza: prima un'ondata canary, un controllo di salute prima di promuovere il resto, poi un'ondata progressiva, con rollback automatico in caso di errore. I nodi offline o sotto la versione minima compatibile vengono saltati. I nodi applicano la loro desired_version e riportano l'esito."],
  "common.errorMsg": ["Error: {error}", "Errore: {error}"],
  "common.status": ["Status", "Stato"],
  "common.detail": ["Detail", "Dettaglio"],
  "fleet.new": ["New deployment", "Nuova distribuzione"],
  "fleet.versionPh": ["Target version (e.g. 1.4.0)", "Versione di destinazione (es. 1.4.0)"],
  "fleet.canary": ["Canary", "Canary"],
  "fleet.minCompatPh": ["Min compatible (optional)", "Minima compatibile (facoltativa)"],
  "fleet.start": ["Start rollout", "Avvia distribuzione"],
  "fleet.none": ["No deployments yet.", "Ancora nessuna distribuzione."],
  "fleet.select": ["Select or start a deployment.", "Seleziona o avvia una distribuzione."],
  "fleet.from": ["from {v}", "da {v}"],
  "fleet.advance": ["Advance / health-gate", "Avanza / controllo salute"],
  "fleet.wave.canary": ["Canary wave", "Ondata canary"],
  "fleet.wave.rollout": ["Rollout wave", "Ondata di distribuzione"],
  "fleet.node": ["Node", "Nodo"],
  "fleet.fromCol": ["From", "Da"],
  "common.invalidJson": ["invalid JSON", "JSON non valido"],
  "common.create": ["Create", "Crea"],
  "env.subtitle": ["Isolated workspaces with a declarative manifest: scope tasks, queries and memory, and snapshot or restore their configuration.", "Spazi di lavoro isolati con un manifest dichiarativo: separano attività, interrogazioni e memoria, e permettono di salvare e ripristinare la configurazione."],
  "env.namePh": ["New environment name…", "Nome del nuovo ambiente…"],
  "env.none": ["No environments yet.", "Ancora nessun ambiente."],
  "env.select": ["Select an environment.", "Seleziona un ambiente."],
  "env.manifest": ["Manifest (JSON)", "Manifest (JSON)"],
  "env.variables": ["Variables (JSON)", "Variabili (JSON)"],
  "env.snapshot": ["Snapshot", "Salva istantanea"],
  "env.snapshots": ["Snapshots", "Istantanee"],
  "env.noSnapshots": ["No snapshots yet.", "Ancora nessuna istantanea."],
  "env.stats": ["tasks {tasks} · memories {mem}", "attività {tasks} · ricordi {mem}"],
  "env.restore": ["Restore", "Ripristina"],
  "models.rec.r1small": ["DeepSeek reasoning — lightweight and suitable for CPU-only hosts", "Ragionamento DeepSeek — leggero e adatto a host solo CPU"],
  "models.rec.r1big": ["★ DeepSeek recommended — stronger reasoning, more RAM required", "★ DeepSeek consigliato — ragionamento migliore, richiede più RAM"],
  "models.rec.qwen3": ["★ Recommended — great in Italian, 3B", "★ Consigliato — ottimo in italiano, 3B"],
  "models.rec.llama3": ["Fast and solid, 3B", "Veloce e affidabile, 3B"],
  "models.rec.gemma2": ["Very fast, 2B", "Molto veloce, 2B"],
  "models.rec.phi": ["Strong reasoning for its size, 3.8B", "Buon ragionamento per le sue dimensioni, 3.8B"],
  "models.rec.qwen7": ["Best quality, slower on CPU, 7B", "Qualità migliore, più lento su CPU, 7B"],
  "models.rec.mistral": ["Solid generalist, 7B", "Generalista solido, 7B"],
  "models.confirmDelete": ["Delete model {name}?", "Eliminare il modello {name}?"],
  "models.none": ["none", "nessuna"],
  "models.subtitle": ["Installed models and a scan of this machine's hardware.", "Modelli installati e analisi dell'hardware di questa macchina."],
  "models.hardware": ["Host hardware", "Hardware dell'host"],
  "models.platform": ["Platform", "Piattaforma"],
  "models.cpuCores": ["CPU cores", "Core CPU"],
  "models.ramTotal": ["RAM total", "RAM totale"],
  "models.ollamaBackend": ["Ollama backend", "Backend Ollama"],
  "models.recommended": ["Recommended models", "Modelli consigliati"],
  "models.recommendedHelp": ["One-click local models served by Ollama, including DeepSeek R1. On a CPU-only host, smaller = faster; larger models give better quality but require more RAM.", "Modelli locali installabili con un clic tramite Ollama, incluso DeepSeek R1. Su un host solo CPU i modelli più piccoli sono più veloci; quelli più grandi danno risposte migliori ma richiedono più RAM."],
  "models.installed": ["installed", "installato"],
  "models.useDefault": ["Use as default", "Usa come predefinito"],
  "models.default": ["default", "predefinito"],
  "models.downloading": ["Downloading…", "Download in corso…"],
  "models.downloadUse": ["Download & use", "Scarica e usa"],
  "models.download": ["Download", "Scarica"],
  "models.any": ["Download any model", "Scarica un altro modello"],
  "models.anyHelp": ["Download any Ollama model by name, e.g.", "Scarica qualsiasi modello Ollama indicandone il nome, per esempio"],
  "models.registered": ["Registered models", "Modelli registrati"],
  "models.refreshing": ["Refreshing…", "Aggiornamento…"],
  "models.refresh": ["Refresh from providers", "Aggiorna dai provider"],
  "models.empty": ["No models yet. Click “Refresh from providers” to discover them.", "Ancora nessun modello. Fai clic su “Aggiorna dai provider” per trovarli."],
  "common.name": ["Name", "Nome"],
  "models.provider": ["Provider", "Provider"],
  "models.family": ["Family", "Famiglia"],
  "models.context": ["Context", "Contesto"],
  "models.available": ["Available", "Disponibile"],
  "common.actions": ["Actions", "Azioni"],
  "models.setDefault": ["Set default", "Imposta predefinito"],
  "v.pulling": ["Downloading", "Download in corso"],
  "v.starting": ["Starting", "Avvio"],
  "v.done": ["Done", "Completato"],
  "rt.endpointPh": ["endpoint (http://host:port)", "endpoint (http://host:porta)"],
  "rt.apiKeyPh": ["API key (encrypted at rest)", "Chiave API (salvata cifrata)"],
  "rt.endpoint": ["Endpoint", "Endpoint"],
  "rt.circuit": ["Circuit breaker", "Circuit breaker"],
  "rt.circuitOpen": ["OPEN (paused after errors)", "APERTO (sospeso dopo errori)"],
  "rt.discover": ["Discover models", "Rileva modelli"],
  "rt.modelKeyPh": ["model_key (e.g. qwen-8b)", "model_key (es. qwen-8b)"],
  "rt.runtimePh": ["runtime…", "runtime…"],
  "rt.runtimeModelPh": ["model name on the runtime", "nome del modello sul runtime"],
  "rt.priority": ["priority", "priorità"],
  "rt.modelKey": ["model_key", "model_key"],
  "rt.runtime": ["runtime", "runtime"],
  "rt.modelName": ["model name", "nome modello"],
  "rt.load": ["loading", "caricamento"],
  "rt.aliasPh": ["alias (e.g. atlas.general)", "alias (es. atlas.general)"],
  "rt.targetsPh": ["model_keys, in order (e.g. qwen-8b, qwen-4b)", "model_key, in ordine (es. qwen-8b, qwen-4b)"],
  "rt.targets": ["targets", "destinazioni"],
  "rt.taskTypePh": ["task type (e.g. coding)", "tipo di attività (es. coding)"],
  "rt.capsPh": ["capabilities (CODING, REASONING)", "capacità (CODING, REASONING)"],
  "rt.preferredPh": ["preferred alias", "alias preferito"],
  "rt.fallbackPh": ["fallback aliases (in order)", "alias di riserva (in ordine)"],
  "rt.route": ["route", "percorso"],
  "llama.title": ["llama.cpp Engine Control", "Controllo motore llama.cpp"],
  "llama.current": ["Current model", "Modello attuale"],
  "llama.load": ["Load", "Carica"],
  "llama.params": ["Inference parameters", "Parametri di inferenza"],
  "llama.context": ["Context (tokens)", "Contesto (token)"],
  "llama.temperature": ["Temperature", "Temperatura"],
  "llama.topP": ["Top-P (nucleus)", "Top-P (nucleus)"],
  "llama.start": ["Start", "Avvia"],
  "llama.stop": ["Stop", "Ferma"],
  "llama.memory": ["Memory", "Memoria"],
  "llama.throughput": ["Throughput", "Velocità"],
  "logs.subtitle": ["Control plane activity and system events", "Attività del control plane ed eventi di sistema"],
  "logs.filterPh": ["Filter by message or level (e.g. 'error', 'deepseek')…", "Filtra per messaggio o livello (es. 'error', 'deepseek')…"],
  "common.refresh": ["Refresh", "Aggiorna"],
  "logs.time": ["Time", "Ora"],
  "logs.level": ["Level", "Livello"],
  "logs.source": ["Source", "Origine"],
  "logs.message": ["Message", "Messaggio"],
  "logs.none": ["No logs found", "Nessun log trovato"],
  "common.showing": ["Showing {from}–{to} of {total}", "Da {from} a {to} di {total}"],
  "common.previous": ["Previous", "Precedente"],
  "common.next": ["Next", "Successiva"],
  "agents.subtitle": ["Autonomous agents running on nodes", "Agenti autonomi in esecuzione sui nodi"],
  "agents.none": ["No agents", "Nessun agente"],
  "agents.noNodes": ["No nodes with agents found", "Nessun nodo con agenti"],
  "common.justNow": ["just now", "adesso"],
  "common.agoD": ["{n}d ago", "{n} g fa"],
  "ap.loop.propose": ["Proposes model improvements", "Propone miglioramenti ai modelli"],
  "ap.loop.experiment": ["Runs A/B experiments", "Esegue esperimenti A/B"],
  "ap.loop.review": ["Reviews its own code", "Revisiona il proprio codice"],
  "ap.loop.fix": ["Prepares sandbox-validated fixes", "Prepara correzioni verificate in sandbox"],
  "ap.every": ["every {n}", "ogni {n}"],
  "ap.onProposal": ["on each new proposal", "a ogni nuova proposta"],
  "ap.onIssue": ["on each new issue", "a ogni nuovo problema"],
  "ap.subtitle": ["What ATLAS is doing on its own: proposing model and code improvements, running experiments and reviewing itself. Everything here only proposes — the irreversible step (apply or merge) always waits for you.", "Cosa fa ATLAS da solo: propone miglioramenti a modelli e codice, esegue esperimenti e si auto-revisiona. Qui tutto è solo una proposta: il passo irreversibile (applicare o unire) aspetta sempre te."],
  "ap.awaiting": ["awaiting your approval", "in attesa della tua approvazione"],
  "ap.canaryEval": ["canary to evaluate", "canary da valutare"],
  "ap.openIssues": ["open code issues", "problemi di codice aperti"],
  "ap.decisions": ["Decisions waiting for you", "Decisioni che aspettano te"],
  "ap.nothing": ["Nothing to decide — ATLAS is caught up.", "Niente da decidere: ATLAS è in pari."],
  "ap.evaluateHint": ["Run the health gate: promote if healthy, otherwise roll back automatically", "Esegue il controllo di salute: promuove se è tutto a posto, altrimenti torna indietro da solo"],
  "ap.evaluate": ["Evaluate canary", "Valuta canary"],
  "ap.canaryHint": ["Roll out to a watched canary, then promote or roll back automatically", "Distribuisce a un canary osservato, poi promuove o torna indietro da solo"],
  "ap.startCanary": ["Start canary", "Avvia canary"],
  "ap.apply": ["Apply", "Applica"],
  "ap.genFixHint": ["Ask a code-capable model to write the fix (needs a coder model; proposal only)", "Chiede a un modello capace di programmare di scrivere la correzione (serve un modello coder; solo proposta)"],
  "ap.genFix": ["Generate fix", "Genera correzione"],
  "ap.review": ["Review", "Esamina"],
  "ap.dismissHint": ["Ignore this code finding", "Ignora questa segnalazione sul codice"],
  "ap.automations": ["Automations running", "Automazioni attive"],
  "ap.off": ["off", "spenta"],
  "ap.counts": ["{issues} code finding(s) · {proposals} proposal(s) · {jobs} fine-tuning job(s)", "{issues} segnalazioni sul codice · {proposals} proposte · {jobs} addestramenti"],
  "ap.activity": ["Recent activity", "Attività recente"],
  "ap.noActivity": ["Nothing yet — automations run on a timer. Give 👍/👎 in chat and download a second model to give ATLAS something to work with.", "Ancora niente: le automazioni partono a intervalli. Dai 👍/👎 in chat e scarica un secondo modello per dare ad ATLAS qualcosa su cui lavorare."],
  "imp.subtitle": ["Semi-automatic: create a proposal and the experiment (candidate vs baseline on an eval suite) runs by itself — this page refreshes until a verdict and an approval appear. You just Approve, then Apply. Safety comes first: a candidate that lowers safety is always a regression.", "Semi-automatico: crea una proposta e l'esperimento (candidato contro modello di riferimento su una suite di valutazione) parte da solo; la pagina si aggiorna finché compaiono un verdetto e una richiesta di approvazione. A te resta solo Approva e poi Applica. La sicurezza viene prima di tutto: un candidato che la peggiora è sempre una regressione."],
  "imp.letPropose": ["Let ATLAS propose", "Lascia proporre ad ATLAS"],
  "imp.letProposeHelp": ["creates a proposal for each available model against the current default, then tests them automatically", "crea una proposta per ogni modello disponibile rispetto a quello predefinito, poi li mette alla prova da sola"],
  "imp.created": ["Created {n} proposal(s); the experiment runs automatically.", "Create {n} proposte; l'esperimento parte da solo."],
  "imp.nothingToPropose": ["Nothing to propose yet — you need at least two models (download another on the Models page). A starter eval suite was created for you.", "Ancora niente da proporre: servono almeno due modelli (scaricane un altro dalla pagina Modelli). Intanto è stata creata una suite di valutazione iniziale."],
  "imp.generate": ["Generate proposals now", "Genera proposte ora"],
  "imp.new": ["New proposal", "Nuova proposta"],
  "imp.titlePh": ["Title (e.g. Adopt llama3.2:3b as default)", "Titolo (es. Usa llama3.2:3b come predefinito)"],
  "imp.suitePh": ["Eval suite (required to experiment)…", "Suite di valutazione (necessaria per l'esperimento)…"],
  "imp.baselinePh": ["Baseline model (blank = current default)", "Modello di riferimento (vuoto = quello predefinito)"],
  "imp.candidatePh": ["Candidate model", "Modello candidato"],
  "imp.create": ["Create proposal", "Crea proposta"],
  "imp.none": ["No proposals yet.", "Ancora nessuna proposta."],
  "imp.select": ["Select a proposal.", "Seleziona una proposta."],
  "imp.candidate": ["Candidate", "Candidato"],
  "imp.vsDefault": ["vs current default", "contro il predefinito attuale"],
  "imp.verdict": ["Verdict", "Verdetto"],
  "imp.deltas": ["Metric changes (candidate − baseline)", "Variazioni delle metriche (candidato − riferimento)"],
  "imp.passRate": ["Pass rate", "Tasso di superamento"],
  "imp.quality": ["Quality", "Qualità"],
  "imp.safety": ["Safety", "Sicurezza"],
  "imp.p95": ["p95 latency", "Latenza p95"],
  "imp.attachSuite": ["Attach an eval suite first", "Prima collega una suite di valutazione"],
  "imp.running": ["Running…", "In esecuzione…"],
  "imp.run": ["Run experiment", "Esegui esperimento"],
  "imp.applyDirect": ["Apply directly", "Applica direttamente"],
  "imp.evaluate": ["Evaluate canary (health check)", "Valuta canary (controllo salute)"],
  "imp.canaryLive": ["Canary live — the candidate is active. Evaluate it to promote it, or roll back automatically on a regression.", "Canary attivo: il candidato è in uso. Valutalo per promuoverlo, oppure si torna indietro da soli in caso di regressione."],
  "imp.healthGate": ["Health check", "Controllo di salute"],
  "imp.awaitingHuman": ["Awaiting a human approval decision.", "In attesa di una decisione di approvazione umana."],
  "rev.subtitle": ["A proposer answers, then a critic looks for flaws, a verifier checks the claims against your reference facts and a judge scores and decides — over several rounds, keeping the best answer by adaptive consensus.", "Un modello risponde, poi un critico cerca i difetti, un verificatore controlla le affermazioni rispetto ai tuoi fatti di riferimento e un giudice assegna un punteggio e decide, su più turni, tenendo la risposta migliore per consenso adattivo."],
  "rev.promptPh": ["Question / prompt to review…", "Domanda o prompt da revisionare…"],
  "rev.refsPh": ["Reference facts the answer should contain (one per line or comma-separated) — optional", "Fatti di riferimento che la risposta deve contenere (uno per riga o separati da virgola) — facoltativo"],
  "rev.maxRounds": ["Max rounds", "Turni massimi"],
  "rev.reviewing": ["Reviewing…", "Revisione in corso…"],
  "rev.run": ["Run review", "Avvia revisione"],
  "rev.none": ["No reviews yet.", "Ancora nessuna revisione."],
  "rev.select": ["Run a review or select one.", "Avvia una revisione o selezionane una."],
  "rev.score": ["score {n}%", "punteggio {n}%"],
  "rev.roundsAgreement": ["{n} round(s) · agreement {pct}%", "{n} turni · accordo {pct}%"],
  "rev.best": ["Best answer", "Risposta migliore"],
  "rev.rounds": ["Rounds", "Turni"],
  "rev.grounding": ["grounding {n}%", "aderenza ai fatti {n}%"],
  "rev.unsupported": ["Unsupported", "Non supportati"],
  "v.severe": ["severe", "grave"],
  "v.major": ["major", "importante"],
  "v.minor": ["minor", "minore"],
  "v.info": ["info", "info"],
  "users.subtitle": ["Roles and access: an admin manages everything, a user just uses the app. Login enforcement is currently", "Ruoli e accessi: un amministratore gestisce tutto, un utente usa solo l'app. L'obbligo di accesso al momento è"],
  "users.on": ["ON", "ATTIVO"],
  "users.off": ["OFF", "DISATTIVO"],
  "users.enableWith": ["Turn it on with", "Attivalo con"],
  "users.afterAdmin": ["once you have created an admin.", "dopo aver creato un amministratore."],
  "users.openMode": ["Open mode: the app has no login and everyone acts as admin. Create an admin here, then set", "Modalità aperta: l'app non richiede accesso e tutti agiscono come amministratore. Crea qui un amministratore, poi imposta"],
  "users.openMode2": ["to require login.", "per rendere obbligatorio l'accesso."],
  "users.add": ["Add a user", "Aggiungi un utente"],
  "users.namePh": ["Full name (optional)", "Nome completo (facoltativo)"],
  "users.passwordPh": ["Password (min 6 characters)", "Password (almeno 6 caratteri)"],
  "users.create": ["Create user", "Crea utente"],
  "users.none": ["No users yet.", "Ancora nessun utente."],
  "users.role": ["Role", "Ruolo"],
  "users.active": ["Active", "Attivo"],
  "users.makeUser": ["Make user", "Rendi utente"],
  "users.makeAdmin": ["Make admin", "Rendi amministratore"],
  "users.deactivate": ["Deactivate", "Disattiva"],
  "users.activate": ["Activate", "Attiva"],
  "set.subtitle": ["Runtime configuration. Changes are saved on the server and take effect immediately — no restart, no .env edit.", "Configurazione in esecuzione. Le modifiche vengono salvate sul server e valgono subito, senza riavvii né modifiche al file .env."],
  "set.language": ["Language", "Lingua"],
  "set.languageHelp": ["Interface language. “Automatic” follows the language of the computer you connect from.", "Lingua dell'interfaccia. “Automatica” segue la lingua del computer da cui ti colleghi."],
  "set.web": ["Web tools", "Strumenti web"],
  "set.provider": ["Search provider", "Motore di ricerca"],
  "set.providerNone": ["none (offline)", "nessuno (offline)"],
  "set.url": ["Search URL", "URL di ricerca"],
  "set.apiKey": ["API key", "Chiave API"],
  "set.isSet": ["set", "impostata"],
  "set.keepKey": ["•••••• (leave blank to keep)", "•••••• (lascia vuoto per mantenerla)"],
  "set.optional": ["optional", "facoltativa"],
  "set.maxResults": ["Max results", "Risultati massimi"],
  "set.timeout": ["Fetch timeout (s)", "Timeout di scaricamento (s)"],
  "set.privateHint": ["Development only — enables SSRF; keep off in production", "Solo per sviluppo: abilita SSRF, tienilo spento in produzione"],
  "set.private": ["Allow private IPs", "Consenti IP privati"],
  "set.allow": ["Allowlist (comma-separated)", "Domini consentiti (separati da virgola)"],
  "set.deny": ["Denylist (comma-separated)", "Domini bloccati (separati da virgola)"],
  "set.saving": ["Saving…", "Salvataggio…"],
  "set.saved": ["Saved", "Salvato"],
  "set.noProvider": ["Web tools are on but no search provider is set, so searches return nothing. Start SearXNG with", "Gli strumenti web sono attivi ma manca un motore di ricerca, quindi le ricerche non restituiscono nulla. Avvia SearXNG con"],
  "set.noProvider2": ["and select it above.", "e selezionalo qui sopra."],
  "sec.namePh": ["NAME (e.g. OPENAI_API_KEY)", "NOME (es. OPENAI_API_KEY)"],
  "sec.cnPh": ["common name (e.g. node-worker-2)", "nome comune (es. node-worker-2)"],
  "cmdk.chat": ["ask anything", "chiedi qualsiasi cosa"],
  "cmdk.dashboard": ["overview", "panoramica"],
  "cmdk.queries": ["background AI runs", "esecuzioni AI in background"],
  "cmdk.queue": ["conversation queue", "coda delle conversazioni"],
  "cmdk.tasks": ["task engine", "motore delle attività"],
  "cmdk.system": ["health", "salute"],
  "cmdk.nodes": ["workers & enrollment", "nodi e registrazione"],
  "cmdk.fleet": ["canary rollout", "distribuzione canary"],
  "cmdk.compliance": ["compliance & remediation", "conformità e correzioni"],
  "cmdk.resources": ["telemetry", "telemetria"],
  "cmdk.models": ["download / default", "scarica / predefinito"],
  "cmdk.runtimes": ["runtimes & routing", "runtime e instradamento"],
  "cmdk.knowledge": ["RAG & memory", "RAG e memoria"],
  "cmdk.environments": ["workspaces", "spazi di lavoro"],
  "cmdk.logs": ["events", "eventi"],
  "cmdk.agents": ["agents on nodes", "agenti sui nodi"],
  "cmdk.autopilot": ["autonomous activity", "attività autonoma"],
  "cmdk.maintenance": ["self-healing", "auto-riparazione"],
  "cmdk.evals": ["quality & safety", "qualità e sicurezza"],
  "cmdk.improvements": ["propose & experiment", "proponi e sperimenta"],
  "cmdk.reviews": ["critic · verify · judge", "critico · verifica · giudice"],
  "cmdk.escalation": ["external help", "aiuto esterno"],
  "cmdk.users": ["roles & access", "ruoli e accessi"],
  "cmdk.security": ["MFA, secrets, certificates", "MFA, segreti, certificati"],
  "cmdk.settings": ["language, web tools & config", "lingua, strumenti web e configurazione"],
  "cmdk.placeholder": ["Jump to… (type a page)", "Vai a… (scrivi una pagina)"],
  "cmdk.empty": ["No matches", "Nessun risultato"],
  "cmdk.foot": ["↑↓ navigate · ↵ open · esc close · ⌘/Ctrl-K toggle", "↑↓ scorri · ↵ apri · esc chiudi · ⌘/Ctrl-K mostra/nascondi"],
  "sys.unavailable": ["System metrics unavailable.", "Metriche di sistema non disponibili."],
  "sys.monitor": ["System monitor", "Monitor di sistema"],
  "sys.cores": ["{n} cores", "{n} core"],
  "sys.load": ["load", "carico"],
  "sys.swap": ["Swap", "Swap"],
  "sys.storage": ["Storage ({path})", "Disco ({path})"],
  "sys.uptime": ["Uptime", "Acceso da"],
  "common.dayShort": ["d", "g"],
  "sys.cpuTemp": ["CPU temperature", "Temperatura CPU"],
  "sys.subtitle": ["Live health of the ATLAS control plane and its dependencies.", "Salute in tempo reale del control plane di ATLAS e dei servizi da cui dipende."],
  "sys.components": ["Components", "Componenti"],
  "sys.overview": ["Overview", "Panoramica"],
  "sys.overall": ["Overall", "Complessivo"],
  "sys.version": ["Version", "Versione"],
  "sys.environment": ["Environment", "Ambiente"],
  "sys.noTasks": ["No tasks yet.", "Ancora nessuna attività."],
  "sys.cluster": ["Cluster (high availability)", "Cluster (alta disponibilità)"],
  "sys.mode": ["Mode", "Modalità"],
  "sys.ha": ["High availability (leader election)", "Alta disponibilità (elezione del leader)"],
  "sys.single": ["single node", "nodo singolo"],
  "sys.thisInstance": ["This instance", "Questa istanza"],
  "sys.leader": ["leader", "leader"],
  "sys.you": ["you", "tu"],
  "sys.follower": ["follower", "secondaria"],
  "tasks.title": ["Tasks & ALMA", "Attività e ALMA"],
  "tasks.subtitle": ["Give ALMA an objective: it breaks it into a graph of subtasks, runs them (independent ones in parallel) and combines the results.", "Dai un obiettivo ad ALMA: lo scompone in un grafo di sotto-attività, le esegue (quelle indipendenti in parallelo) e ne combina i risultati."],
  "tasks.objectivePh": ["e.g. Prepare release notes for v0.1", "es. Prepara le note di rilascio per la v0.1"],
  "tasks.run": ["Run with ALMA", "Esegui con ALMA"],
  "tasks.titleCol": ["Title", "Titolo"],
  "tasks.where": ["Where", "Dove"],
  "tasks.retries": ["Retries", "Tentativi"],
  "tasks.local": ["local", "locale"],
  "tasks.hide": ["Hide", "Nascondi"],
  "tasks.subtasks": ["Subtasks", "Sotto-attività"],
  "tasks.subtasksDag": ["Subtasks (graph)", "Sotto-attività (grafo)"],
  "tasks.noSubtasks": ["No subtasks yet — ALMA may still be planning.", "Ancora nessuna sotto-attività: ALMA potrebbe star ancora pianificando."],
  "queue.title": ["Conversation queue", "Coda delle conversazioni"],
  "queue.subtitle": ["Per-conversation flow control: messages are sent immediately when idle, queued when busy, consecutive messages are merged, and parallelism is capped.", "Controllo del flusso per ogni conversazione: i messaggi partono subito se è libera, vanno in coda se è occupata, quelli consecutivi vengono uniti e il parallelismo è limitato."],
  "queue.cid": ["Conversation id", "ID conversazione"],
  "queue.msgPh": ["Message to enqueue…", "Messaggio da mettere in coda…"],
  "queue.enqueue": ["Enqueue", "Metti in coda"],
  "queue.complete": ["Complete turn", "Completa turno"],
  "queue.stats": ["pending: {pending} · active conversations: {active}", "in attesa: {pending} · conversazioni attive: {active}"],
  "queue.none": ["No pending messages.", "Nessun messaggio in attesa."],
  "queue.merged": ["merged ×{n}", "uniti ×{n}"],
  "q.subtitle": ["Saved AI queries that run in the background: they keep going if you leave, can be stopped mid-way and survive a restart.", "Interrogazioni AI salvate che girano in background: continuano anche se esci, si possono fermare a metà e sopravvivono a un riavvio."],
  "q.promptPh": ["Ask something to run in the background…", "Chiedi qualcosa da eseguire in background…"],
  "q.run": ["Run", "Esegui"],
  "q.none": ["No queries yet.", "Ancora nessuna interrogazione."],
  "q.select": ["Select a query to see its result and events.", "Seleziona un'interrogazione per vederne risultato ed eventi."],
  "q.tokens": ["{n} tokens", "{n} token"],
  "common.cancel": ["Cancel", "Annulla"],
  "q.prompt": ["Prompt", "Richiesta"],
  "q.noOutput": ["No output yet…", "Ancora nessun risultato…"],
  "q.events": ["Events", "Eventi"],
  "kb.title": ["Knowledge (RAG)", "Conoscenza (RAG)"],
  "kb.subtitle": ["Index documents and retrieve relevant passages with citations.", "Indicizza documenti e recupera i passaggi pertinenti con le citazioni."],
  "kb.add": ["Add a document", "Aggiungi un documento"],
  "kb.textPh": ["Paste document text…", "Incolla il testo del documento…"],
  "kb.index": ["Index document", "Indicizza documento"],
  "kb.indexed": ["{n} document(s) indexed", "{n} documenti indicizzati"],
  "kb.ask": ["Ask the knowledge base", "Interroga la base di conoscenza"],
  "kb.questionPh": ["Ask a question…", "Fai una domanda…"],
  "kb.search": ["Search", "Cerca"],
  "kb.score": ["score {n}", "punteggio {n}"],
  "kb.source": ["source: {s}", "fonte: {s}"],
  "kb.memory": ["Memory", "Memoria"],
  "kb.memorySubtitle": ["Durable facts with their origin and an expiry policy.", "Fatti duraturi con la loro origine e una regola di scadenza."],
  "kb.remember": ["Remember a fact", "Ricorda un fatto"],
  "kb.rememberPh": ["Something to remember…", "Qualcosa da ricordare…"],
  "kb.sourcePh": ["source", "fonte"],
  "kb.pin": ["pin", "fissa"],
  "kb.prune": ["Remove expired", "Rimuovi scaduti"],
  "kb.recall": ["Recall", "Richiama"],
  "kb.recallPh": ["Recall a memory…", "Richiama un ricordo…"],
  "kb.recallBtn": ["Recall", "Richiama"],
  "kb.importance": ["importance {n}", "importanza {n}"],
  "v.fact": ["fact", "fatto"],
  "v.preference": ["preference", "preferenza"],
  "v.note": ["note", "nota"],
  "v.episodic": ["episodic", "episodico"],
  "kb.pruned": ["Removed {n} expired memories.", "Rimossi {n} ricordi scaduti."],
  "comp.subtitle": ["Set the desired state of the fleet, see differences at a glance and fix them in one click. Version drift can be fixed automatically and safely; offline nodes and missing capabilities are shown for you to decide.", "Imposta lo stato desiderato della flotta, vedi subito le differenze e correggile con un clic. Le versioni disallineate si possono correggere in automatico in sicurezza; nodi offline e capacità mancanti vengono mostrati perché decida tu."],
  "comp.nodes": ["{n}/{total} nodes", "{n}/{total} nodi"],
  "comp.drifted": ["Drifted", "Disallineati"],
  "comp.minMet": ["Minimum online reached", "Minimo di nodi online raggiunto"],
  "comp.auto": ["Automatic fix", "Correzione automatica"],
  "comp.autoHelp": ["Brings nodes with the wrong version back to the desired one. Safe: it never touches offline or quarantined nodes.", "Riporta alla versione desiderata i nodi con la versione sbagliata. Sicuro: non tocca mai nodi offline o in quarantena."],
  "comp.autoNow": ["Fix automatically now", "Correggi ora in automatico"],
  "comp.desired": ["Desired state", "Stato desiderato"],
  "comp.targetPh": ["Target version", "Versione di destinazione"],
  "comp.capsPh": ["Required capabilities (comma-separated)", "Capacità richieste (separate da virgola)"],
  "comp.minOnline": ["Min online", "Minimo online"],
  "comp.diagnosis": ["Diagnosis", "Diagnosi"],
  "comp.fix": ["Fix", "Correzione"],
  "comp.compliant": ["compliant", "conforme"],
  "comp.drift": ["drift", "disallineato"],
  "v.version_drift": ["version drift", "versione disallineata"],
  "v.capability_missing": ["capability missing", "capacità mancante"],
  "res.subtitle": ["Node telemetry from their periodic signals, and Ollama response times.", "Telemetria dei nodi dai loro segnali periodici e tempi di risposta di Ollama."],
  "res.none": ["No telemetry yet — nodes report it with each heartbeat.", "Ancora nessuna telemetria: i nodi la inviano a ogni segnale periodico."],
  "res.load": ["Load (1 min)", "Carico (1 min)"],
  "res.freeRam": ["Free RAM", "RAM libera"],
  "res.perf": ["Ollama performance", "Prestazioni di Ollama"],
  "res.noPerf": ["No inference recorded yet.", "Ancora nessuna inferenza registrata."],
  "res.model": ["Model", "Modello"],
  "res.calls": ["Calls", "Chiamate"],
  "res.avg": ["Avg ms", "Media ms"],
  "mnt.subtitle": ["Semi-automatic: a new issue is analysed and a fix is prepared and checked in a real, isolated sandbox on its own (this page refreshes as it goes). You just Approve, then Apply. Only after your approval is a pull request opened — it never touches main and never merges. Git actions are guarded and audited (simulated unless GitHub is explicitly enabled).", "Semi-automatico: un nuovo problema viene analizzato e una correzione viene preparata e verificata da sola in una sandbox reale e isolata (la pagina si aggiorna man mano). A te resta solo Approva e poi Applica. Solo dopo la tua approvazione viene aperta una pull request: non tocca mai main e non unisce mai nulla. Le azioni Git sono protette e tracciate (simulate finché GitHub non è abilitato esplicitamente)."],
  "mnt.selfReview": ["Self-review — improve my own code", "Auto-revisione — migliora il mio codice"],
  "mnt.selfReviewHelp": ["ATLAS scans its own source (lint, TODO/FIXME, oversized files) and files each finding as an issue awaiting approval. It runs automatically; this starts a manual scan.", "ATLAS analizza il proprio codice (lint, TODO/FIXME, file troppo lunghi) e registra ogni segnalazione come problema in attesa di approvazione. Parte da solo; questo avvia un'analisi manuale."],
  "mnt.scanned": ["Scanned {files} file(s): {findings} finding(s), {issues} new issue(s).", "Analizzati {files} file: {findings} segnalazioni, {issues} nuovi problemi."],
  "mnt.scanNow": ["Scan my code now", "Analizza il mio codice ora"],
  "mnt.issues": ["{n} issue(s)", "{n} problemi"],
  "mnt.select": ["Select an issue to see details.", "Seleziona un problema per vederne i dettagli."],
  "mnt.service": ["Service", "Servizio"],
  "mnt.severity": ["Severity", "Gravità"],
  "mnt.occurrences": ["Occurrences", "Occorrenze"],
  "mnt.analyze": ["Analyze", "Analizza"],
  "mnt.createFix": ["Create fix", "Crea correzione"],
  "mnt.run": ["Run", "Esecuzione"],
  "mnt.branch": ["Branch", "Branch"],
  "mnt.applyFix": ["Apply approved fix (open PR)", "Applica la correzione approvata (apre la PR)"],
  "mnt.applyHelp": ["Governed action: opens the PR through the configured provider (simulated unless GitHub is enabled). Never pushes to a protected branch and never merges.", "Azione controllata: apre la PR tramite il provider configurato (simulata finché GitHub non è abilitato). Non scrive mai su un branch protetto e non unisce mai nulla."],
  "mnt.approvalRequired": ["Approval required", "Approvazione richiesta"],
  "ft.title": ["Fine-tuning (self-improvement)", "Fine-tuning (auto-miglioramento)"],
  "ft.subtitle": ["Turn ATLAS's own good answers into a better model, locally: build a dataset from chat replies you rated 👍, train a LoRA adapter on a GPU node, then adopt it through the same evaluation and canary checks as any other change. Nothing leaves your machines, and the model only becomes the default if it actually wins.", "Trasforma le buone risposte di ATLAS in un modello migliore, in locale: crea un dataset dalle risposte in chat valutate 👍, addestra un adattatore LoRA su un nodo con GPU, poi adottalo con gli stessi controlli di valutazione e canary di qualsiasi altra modifica. Nulla esce dalle tue macchine e il modello diventa predefinito solo se vince davvero."],
  "ft.readiness": ["Readiness", "Prerequisiti"],
  "ft.gpuNode": ["GPU training node", "Nodo GPU per l'addestramento"],
  "ft.noneOnline": ["none online", "nessuno online"],
  "ft.positive": ["Positive feedback available", "Valutazioni positive disponibili"],
  "ft.needGpu": ["Fine-tuning trains on a real GPU. Add a node that advertises the", "Il fine-tuning addestra su una GPU vera. Aggiungi un nodo che dichiari la capacità"],
  "ft.needGpu2": [" capability, or run a job as a dry run to test the whole pipeline without training.", " oppure esegui un'attività di prova per testare tutto il processo senza addestrare."],
  "ft.newDataset": ["New dataset", "Nuovo dataset"],
  "ft.namePh": ["Name (e.g. Good IT answers)", "Nome (es. Buone risposte IT)"],
  "ft.basePh": ["Base model (optional, blank = default)", "Modello di base (facoltativo, vuoto = predefinito)"],
  "ft.none": ["No datasets yet.", "Ancora nessun dataset."],
  "ft.select": ["Select or create a dataset.", "Seleziona o crea un dataset."],
  "ft.base": ["Base model", "Modello di base"],
  "ft.currentDefault": ["current default", "predefinito attuale"],
  "ft.included": ["Included examples", "Esempi inclusi"],
  "ft.recommended": ["{n} recommended", "{n} consigliati"],
  "ft.harvestHint": ["Collect chat replies rated 👍 into this dataset", "Raccoglie in questo dataset le risposte in chat valutate 👍"],
  "ft.added": ["Added {n} example(s) from positive feedback.", "Aggiunti {n} esempi dalle valutazioni positive."],
  "ft.nothingToHarvest": ["No new positively rated replies yet — give 👍 to good chat answers first.", "Ancora nessuna nuova risposta valutata positivamente: prima dai 👍 alle risposte buone in chat."],
  "ft.harvest": ["Collect from feedback", "Raccogli dalle valutazioni"],
  "ft.trainHint": ["Send a LoRA training job to the GPU node", "Invia un addestramento LoRA al nodo GPU"],
  "ft.trainNoGpu": ["No GPU node online — the job will wait for one (or fail explicitly)", "Nessun nodo GPU online: l'attività ne aspetterà uno (o fallirà dichiarandolo)"],
  "ft.dispatched": ["Training job sent — it runs on a GPU node.", "Addestramento inviato: gira su un nodo GPU."],
  "ft.train": ["Train LoRA adapter", "Addestra adattatore LoRA"],
  "ft.jobs": ["Training jobs", "Addestramenti"],
  "ft.examplesShort": ["{n} ex.", "{n} es."],
  "ft.loss": ["loss {n}", "loss {n}"],
  "ft.adoptHint": ["Propose this adapter as the new default (subject to evaluation and canary)", "Proponi questo adattatore come nuovo predefinito (soggetto a valutazione e canary)"],
  "ft.adopted": ["Created an improvement proposal — review it under Improvements; it must beat the current model and pass the canary health check.", "Creata una proposta di miglioramento: controllala in Miglioramenti. Deve battere il modello attuale e superare il controllo di salute del canary."],
  "ft.adopt": ["Adopt", "Adotta"],
  "ft.addByHand": ["Add an example by hand", "Aggiungi un esempio a mano"],
  "ft.promptPh": ["Prompt (user)", "Richiesta (utente)"],
  "ft.responsePh": ["Ideal response (assistant)", "Risposta ideale (assistente)"],
  "ft.addExample": ["Add example", "Aggiungi esempio"],
  "ft.examples": ["Examples ({n})", "Esempi ({n})"],
  "ft.noExamples": ["None yet — collect from feedback or add one by hand.", "Ancora nessuno: raccoglili dalle valutazioni o aggiungine uno a mano."],
  "ft.include": ["include", "includi"],
  "ft.q": ["Q", "D"],
  "ft.a": ["A", "R"],
  "v.feedback": ["feedback", "valutazione"],
  "v.manual": ["manual", "manuale"],
  "ev.subtitle": ["Evaluation suites for quality, safety and performance. Runs use the active model; mark one as the baseline to compare against.", "Suite di valutazione per qualità, sicurezza e prestazioni. Le esecuzioni usano il modello attivo; segnane una come riferimento per i confronti."],
  "ev.namePh": ["New suite name…", "Nome della nuova suite…"],
  "ev.create": ["Create suite", "Crea suite"],
  "ev.none": ["No suites yet.", "Ancora nessuna suite."],
  "ev.select": ["Select a suite.", "Seleziona una suite."],
  "ev.addCase": ["Add a case", "Aggiungi un caso"],
  "ev.inputPh": ["Prompt / input…", "Richiesta / input…"],
  "ev.expectedPh": ["Expected text fragments (comma-separated)", "Frammenti di testo attesi (separati da virgola)"],
  "ev.addCaseBtn": ["Add case", "Aggiungi caso"],
  "ev.runBaseline": ["Run as baseline", "Esegui come riferimento"],
  "ev.runs": ["Runs", "Esecuzioni"],
  "ev.noRuns": ["No runs yet.", "Ancora nessuna esecuzione."],
  "ev.when": ["When", "Quando"],
  "ev.pass": ["Passed", "Superati"],
  "ev.latency": ["Latency", "Latenza"],
  "ev.baseline": ["baseline", "riferimento"],
  "esc.title": ["Manual escalation", "Escalation manuale"],
  "esc.subtitle": ["Prepare a self-contained package to paste into ChatGPT Plus or Claude Pro, then import the reply. Imported replies are untrusted until you validate them. ATLAS never automates the browser session.", "Prepara un pacchetto autosufficiente da incollare in ChatGPT Plus o Claude Pro, poi importa la risposta. Le risposte importate non sono affidabili finché non le convalidi. ATLAS non automatizza mai la sessione del browser."],
  "esc.objectivePh": ["Objective…", "Obiettivo…"],
  "esc.logsPh": ["Logs / context (optional)", "Log / contesto (facoltativo)"],
  "esc.prepare": ["Prepare package", "Prepara pacchetto"],
  "esc.recent": ["Recent", "Recenti"],
  "esc.select": ["Prepare or select an escalation.", "Prepara o seleziona un'escalation."],
  "esc.copyInto": ["Copy this into {target}", "Copia questo in {target}"],
  "esc.copied": ["Copied!", "Copiato!"],
  "esc.pasteBack": ["Paste the reply back", "Incolla qui la risposta"],
  "esc.responsePh": ["Paste the model's response…", "Incolla la risposta del modello…"],
  "esc.import": ["Import response", "Importa risposta"],
  "esc.imported": ["Imported response", "Risposta importata"],
  "esc.untrusted": ["NOT TRUSTED", "NON AFFIDABILE"],
  "esc.trusted": ["trusted", "affidabile"],
  "esc.validate": ["Validate", "Convalida"],
  "setup.nodeEndpointPh": ["node endpoint (e.g. http://10.147.x.x:11434)", "endpoint del nodo (es. http://10.147.x.x:11434)"],
  "v.task_success_rate": ["Task success rate", "Attività riuscite"],
  "v.nodes_online_ratio": ["Nodes online", "Nodi online"],
  "v.control_plane_healthy": ["Control plane healthy", "Control plane in salute"],
};
